services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: fittrack-oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: GarminDocker123
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data: