CREATE OR REPLACE TRIGGER HEALTH_METRIC_BI
BEFORE INSERT ON HEALTH_METRIC
FOR EACH ROW
WHEN (NEW.METRICID IS NULL)
BEGIN
    SELECT HEALTH_METRIC_SEQ.NEXTVAL
    INTO :NEW.METRICID
    FROM DUAL;
END;